### ISSUE TITLE
Css broken in ie9

### ISSUE THREAD

**Issue by davemathews** [FrozenNode/Laravel-Administrator#314]
here is the administration.css fix for ie9 please see below and consider adding to the code base.  we are using the view composer to overwrite it for the fix until its done.  Basically in IE 9 the navigation dropdowns do not fire off.

``` css
@import url(http://fonts.googleapis.com/css?family=Oxygen:400,700&subset=latin-ext,latin);
.verdana {
  font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
}
...removed the rest due to length
```
